baseURL = "https://mickey.dev"
title = "Josh Michielsen (Jmickey)"
theme = "KeepItNew"
copyright = "2019 Josh Michielsen"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true
googleAnalytics = "UA-140141781-1"
pygmentsUseClasses = true
pygmentsCodefences = true

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "jmickey"

  [params.publisher]
    name = "jmickey"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "/logo.png"
    width = 127
    height = 40

  [params.image]
    url = "/cover.jpg"
    width = 800
    height = 600

[Permalinks]
  posts = "/posts/:slug"
  code = "/go/:filename"

  [menu]
    [[menu.main]]
      name = "Blog"
      url = "/posts/"
      weight = 1

    [[menu.main]]
      name = "About"
      url = "/about"
      weight = 2

    [[menu.main]]
      name = "Talks"
      url = "/talks"
      weight = 3

    [[menu.main]]
      name = "Resume"
      url = "/Resume"
      weight = 4

[params]
  author = "Josh Michielsen"
  subtitle = "Senior Software Engineer @ Snyk"
  subtitle_additional = "Software Engineering, Kubernetes, TypeScript, Go, Container Security"
  subtitle_additional_2 = "Cycling, Photography, Coffee"
  description = "Aussie ðŸ‡¦ðŸ‡º in Cambridge ðŸ‡¬ðŸ‡§. Senior Software Engineer, Snyk. Previously Platforms and Kubernetes at CondÃ© Nast. #doge owner. Photographer ðŸ“·"
  socialShare = true

[params.gravatar]
    email = "j@mickey.dev"

[params.social]
  Github = "jmickey"
  Linkedin = "jmichielsen"
  Twitter = "jmickey_"
  Email = "j@mickey.dev"
  Strava = "32368360"
  Keybase = "jmickey"

[params.share]
  Twitter = true
  Linkedin = true
  Reddit = true
  HackerNews = true
  Facebook = true

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
